@echo off
echo 🔄 Reiniciando backend completamente...

echo 📍 Deteniendo todos los procesos Node.js...
taskkill /F /IM node.exe 2>nul

echo 🛠️  Compilando TypeScript...
npm run build

echo 🚀 Iniciando servidor desde JavaScript compilado...
start cmd /k "node dist/app.js"

echo ⏱️  Esperando 5 segundos para que el servidor inicie...
timeout /t 5 /nobreak

echo 🧪 Probando API...
node test-api-products-names.js

echo ✅ Script completado. Presiona cualquier tecla para continuar...
pause
